# --------------------------------------
#        DESTROY THE MONUMENT (1.0)
#
#        Built by Niklas Haiminen
#       for Smath Game Development
#         http://smath.fi/games
#
#     Please follow the instructions and
#      descriptions of every setting!
#
#    Our Discord: smath.fi/games/discord
#        Wiki: smath.fi/games/dtm
# --------------------------------------

# --------------------------
#     DATABASE SETTINGS
# --------------------------

# Set if the MySQL database option is enabled.
# If not, the plugin will detect it automatically
# and use the SQLite option instead.
mysql:
  enabled: false
  address: localhost
  port: 3306
  username: root
  password: 1234
  database: Minecraft

# Log the sent SQL queries to the console (for debugging mainly)
log-queries: true

# Settings for auto-saving data of players
# Changing this requires server restart!
auto-saving:
  enabled: true
  # How often should the server save the data (in seconds)
  interval: 300

# --------------------------
#      SERVER SETTINGS
# --------------------------

# For debugging/error fixing purposes
# Logs plugin-events to the console
logging: true

# Notify server admins (players with OP)
# if there's a new update available
notify-updates: true

# Select the date format that the server uses
date-format: 'mm/dd/yyyy'

# Global game settings
games:
  # The minimum amount of players that is needed to start the game
  min-players-to-start: 2

# Spawn settings
# DO NOT MODIFY THESE SETTINGS, UNLESS YOU KNOW
# WHAT YOU'RE DOING!
# These settings DO NOT contain any documentation, as because
# they're not meant to be modified!
# NOTICE! The spawn works as the 'lobby', as you teleport to spawn to
# wait for the next game for example
spawn:
  teleport-on-join: true
  location:
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: '0.0'
    pitch: '0.0'
    world: world


# Settings for the server's scoreboard
scoreboard:
  enabled: true
  title: "&a&lDTM ยง7- %dtm_version%"
  scoreboard:
    - ' &7Wins: &a%wins%'
    - ' &7Losses: &a%losses%'
    - ' &7Credits: &e%points%'
    - ' '
    - ' &7K/D: &a%kd_ratio%'
    - ' &7Ping: &e%ping%ms'
    - ' '
    - ' &asmath.fi/dtm'

# Settings for server weather
weather:
  lock: true
  # Values: RAINY or SUNNY
  weather-lock: SUNNY

# --------------------------
#       GAME SETTINGS
# --------------------------

# Settings for spectators
spectating:
  # Toggle if player's can spectate games
  enabled: true
  # If this is true, all commands are disabled, except
  # the commands listed in 'enabled-commands' list.
  disable-all-commands: true
  enabled-commands:
    - spawn
    - hub
    - join
    - next

# Message sent to a player when it joins a game,
# telling the goal of the game.
game-description-message:
  enabled: true
  message:
    - '&7&m--------------------'
    - ' &a&lDestroyTheMonument &7(%dtm_version%)'
    - ''
    - ' &a&lGoal: '
    - ' &7There is &a2 teams &7and each one'
    - ' &7has &a1 monument&7! Each team tries'
    - ' &7to destroy the other''s monument and'
    - ' &7after it''s destroyed kill the other'
    - ' &ateam''s players&7! After the monument is'
    - ' &7gone, you cannot respawn!'
    - ''
    - '&7&m--------------------'

# Different messages for game countdown
game-countdown:
  start-message: '&e&lGame countdown started!'
  message: '&eGame starting in &a%seconds_left%&e...'
  countdown-stopped: '&aStopped game countdown!'

# Different messages to events inside the game
game-messages:
  game-starting: '&e&lStarting game...'
  game-paused: '&e&lGame paused! Waiting to resume...'
  game-resumed: '&e&lGame continues!'

# Message when game ends, announcing the winner team
game-end-message:
  - '&7&m--------------------'
  - ' &a&lGame is Over!'
  - ''
  - ' &7Winner: %winner_team%&7!'
  - ''
  - ' &7Teleporting to lobby...'
  - '&7&m--------------------'


# --------------------------
#       SHOP SETTINGS
#     (Coming soon...)
# --------------------------

#          ....


# --------------------------
#       GUI SETTINGS
# --------------------------

#         ...


# --------------------------
#       CHAT SETTINGS
# --------------------------

# Settings for the prefix in-front-of every sent message
msg-prefix: "&a[DTM]"
msg-prefix-enabled: true

# The join and leave messages for the server as a whole and
# for the individual games. These messages can be toggled
connection-messages:
  server-join:
    enabled: true
    message: "&7[&a+&7] The player &a%player% &7joined the server!"
  server-quit:
     enabled: true
     message: "&7[&c-&7] The player &a%player% &7left the server!"
  game-joined:
    enabled: true
    message: "&eThe player &a%player% &ejoined the game!"
  game-quit:
     enabled: true
     message: "&eThe player &a%player% &equit the game!"

# The chat-format created by DTM
# For info about the placeholders, see our wiki!
chat-format:
  # Whether you want to use this plugin's chat-format
  enabled: true
  # The actual formatting for chat messages
  # For placeholder info, see the wiki
  format: '&8[&b%points%&8] &7%player%&f: %message%'
  # Enable players to use chat color in chat (&e, &a, &c, etc.)
  colors:
    # Whether you want to enable this setting or not
    enabled: true
    # Enable this, if you only want players with permission to use colors
    # (the permission is dtm.chat.color)
    only-for-permission-holders: true

# Settings for chat messages
chat:
  # Whether the chat is enabled or not
  enabled: true
  # Settings for delaying the chat
  delay:
    # Whether this setting is enabled or not
    enabled: true
    # The actual delay between messages (in seconds)
    delay: 3
  # Whether you want to disable chat during a game
  disable-chat-in-game: false
  # Whether you want to disable chat whilst waiting the game to start (in lobby)
  disable-chat-in-lobby: false

# The message sent to player as they join
message-of-today:
  enabled: true
  motd:
    - '&7&m--------------------'
    - ' &a&lDestroyTheMonument &7(%dtm_version%)'
    - ''
    - ' &7Built by &a(c) Niklas Haiminen'
    - ' &7Powered by &aSmath Ay'
    - ' '
    - ' &7Wiki: &ahttp://smath.fi/games/dtm'
    - ' &7Discord: &ahttp://smath.fi/games/discord'
    - '&7&m--------------------'


# Every chat message in the game itself
# Notice that these are exclusively the
# chat-messages sent to the player.
# Other notifications, join-messages, etc.
# can be found under the 'Chat Settings'.
# These messages cannot be switched off.
messages:
  no-permission: "&cI'm sorry, but you do not have the permission to do this!"
  data-saved: "&eSaved your data automatically!"
  command-for-players: "&cThis command can only be used by players!"
  feature-not-available: '&eThis feature is not available'
  game-running-error: '&cYou cannot join the game because it is already running! You can spectate the game with &e/spec&c!'
  teleport-to-spawn: '&eTeleporting you to spawn...'



