# --------------------------------------
#        DESTROY THE MONUMENT (1.0)
#
#        Built by Niklas Haiminen
#       for Smath Game Development
#         http://smath.fi/games
#
#     Please follow the instructions and
#      descriptions of every setting!
#
#    Our Discord: smath.fi/games/discord
#        Wiki: smath.fi/games/dtm
# --------------------------------------

# --------------------------
#     DATABASE SETTINGS
# --------------------------

# Set if the MySQL database option is enabled.
# If not, the plugin will detect it automatically
# and use the SQLite option instead.
mysql:
  enabled: false
  address: localhost
  port: 3306
  username: root
  password: 1234
  database: Minecraft

# Settings for auto-saving data of players
# Changing this requires server restart!
auto-saving:
  enabled: true
  # How often should the server save the data (in seconds)
  interval: 120

# --------------------------
#      SERVER SETTINGS
# --------------------------

# For debugging/error fixing purposes
# Logs plugin-events to the console
logging: true

# Notify server admins (players with OP)
# if there's a new update available
notify-updates: true

# Select the date format that the server uses
date-format: 'mm/dd/yyyy'

# Global game settings
games:
  # The amount of games that can be run at the same time
  max-running-games: 5
  # The minimum amount of players that is needed to start the game
  min-players-to-start: 6
  # The maximum amount of players for a game
  max-player-per-game: 30

# Spawn settings
# DO NOT MODIFY THESE SETTINGS, UNLESS YOU KNOW
# WHAT YOU'RE DOING!
# These settings DO NOT contain any documentation, as because
# they're not meant to be modified!
spawn:
  teleport-on-join: true
  location:
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: '0.0'
    pitch: '0.0'
    world: world

scoreboard:
  enabled: true
  title: "&a&lDTM ยง7- %dtm_version%"
  scoreboard:
    - ' &7Wins: &a%wins%'
    - ' &7Losses: &a%losses%'
    - ' &7Credits: &e%credits%'
    - ' '
    - ' &7K/D: &a%kd_ratio%'
    - ' &7Ping: &e%ping%ms'
    - ' '
    - ' &asmath.fi/dtm'

# Settings for server weather
weather:
  lock: true
  # Values: RAINY or SUNNY
  weather-lock: SUNNY

# --------------------------
#       GAME SETTINGS
# --------------------------

# Settings for spectators
spectating:
  # Toggle if player's can spectate games
  enabled: true
  # If this is true, all commands are disabled, except
  # the commands listed in 'enabled-commands' list.
  disable-all-commands: true
  enabled-commands:
    - spawn
    - hub
    - join
    - next

# --------------------------
#       SHOP SETTINGS
#     (Coming soon...)
# --------------------------

#          ....


# --------------------------
#       GUI SETTINGS
# --------------------------

#         ...


# --------------------------
#       CHAT SETTINGS
# --------------------------

# Settings for the prefix in-front of every sent message
msg-prefix: "&a[DTM]"
msg-prefix-enabled: true

# The join and leave messages for the server as a whole and
# for the individual games. These messages can be toggled
connection-messages:
  server-join:
    enabled: true
    message: "&7[&a+&7] The player &a%player% &7joined the server!"
  server-quit:
     enabled: true
     message: "&7[&c-&7] The player &a%player% &7left the server!"
  game-joined:
    enabled: true
    message: "&eThe player &a%player% &ejoined the game! (%current_players%/%max_players%)"
  game-quit:
     enabled: true
     message: "&eThe player &a%player% &equit the game! (%current_players%/%max_players%)"

message-of-today:
  enabled: true
  motd:
    - '&7&m--------------------'
    - ' &a&lDestroyTheMonument &7(%dtm_version%)'
    - ''
    - ' &7Built by &a(c) Niklas Haiminen'
    - ' &7Powered by &aSmath Ay'
    - ' '
    - ' &7Wiki: &ahttp://smath.fi/games/dtm'
    - ' &7Discord: &ahttp://smath.fi/games/discord'
    - '&7&m--------------------'


# Every chat message in the game itself
# Notice that these are exclusively the
# chat-messages sent to the player.
# Other notifications, join-messages, etc.
# can be found under the 'Chat Settings'.
# These messages cannot be switched off.
messages:
  no-permission: "&cI'm sorry, but you do not have the permission to do this!"
  data-saved: "&aSaved your data automatically!"
  command-for-players: "&cThis command can only be used by players!"


